
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Franquisia1._1
{

using System;
    using System.Collections.Generic;
    
public partial class anexos
{

    public string idcia { get; set; }

    public string tipane { get; set; }

    public string codane { get; set; }

    public string desane { get; set; }

    public string refane { get; set; }

    public string rucane { get; set; }

    public string tipdoc { get; set; }

    public string nrodoc { get; set; }

    public string repane { get; set; }

    public string carane { get; set; }

    public string provane { get; set; }

    public string depane { get; set; }

    public string paisane { get; set; }

    public string posane { get; set; }

    public string telane { get; set; }

    public string situane { get; set; }

    public string fcrea { get; set; }

    public string fmod { get; set; }

    public string usuario { get; set; }

    public string is_renigv { get; set; }

    public string entfin { get; set; }

    public string nrocta { get; set; }

    public string mon { get; set; }

    public string tipcta { get; set; }

    public string ctaane { get; set; }

    public string alma_mp { get; set; }

    public string is_mp { get; set; }

    public string tipo_caja { get; set; }

    public string is_servicio { get; set; }

    public string alma_pt { get; set; }

    public string tipper { get; set; }

    public string apepat { get; set; }

    public string apemat { get; set; }

    public string nombre1 { get; set; }

    public string nombre2 { get; set; }

    public byte[] foto { get; set; }

    public string is_domiciliado { get; set; }

    public string apliconve { get; set; }

    public string convenio { get; set; }

    public string corto { get; set; }

    public string procmp { get; set; }

    public string subprocmp { get; set; }

    public string codaux { get; set; }

}

}
