//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ciafile
    {
        public string idcia { get; set; }
        public string descia { get; set; }
        public string ruccia { get; set; }
        public string repcia { get; set; }
        public string shortcia { get; set; }
        public string typecia { get; set; }
        public string statecia { get; set; }
        public string regpatcia { get; set; }
        public string dircia { get; set; }
        public string desSi { get; set; }
        public string desNo { get; set; }
        public string actividad { get; set; }
        public string reglab { get; set; }
        public string codaux { get; set; }
        public byte[] logo { get; set; }
        public string ispresupuesto { get; set; }
        public string tipdoc { get; set; }
        public string nrodoc { get; set; }
        public string floid { get; set; }
        public string plancuentas { get; set; }
        public string regtributario { get; set; }
        public string telefonos { get; set; }
        public string website { get; set; }
        public string cargorep { get; set; }
        public string kcatalogo { get; set; }
        public string kmetval { get; set; }
        public string ubigeo { get; set; }
        public string nombrecomercial { get; set; }
        public string eslogan { get; set; }
        public string linkconsulta { get; set; }
        public string resintendencia { get; set; }
    }
}
