//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class conc
    {
        public string CODCIA { get; set; }
        public string CODIGO { get; set; }
        public string SUCURSAL { get; set; }
        public string UNDATENCION { get; set; }
        public string PERATENCION { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public string SITUACION { get; set; }
        public string USER { get; set; }
    }
}
