//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class conventa
    {
        public string codcia { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string claserv { get; set; }
        public string is_equialm { get; set; }
        public string equivalencia { get; set; }
        public string cuenta { get; set; }
        public byte[] foto { get; set; }
        public string situa { get; set; }
        public byte[] foto64 { get; set; }
        public string tipovalorventa { get; set; }
    }
}
