//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class forpago
    {
        public string codcia { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public string is_tarjeta { get; set; }
        public string situa { get; set; }
    }
}
