//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class maesgen
    {
        public string idmaesgen { get; set; }
        public string clavemaesgen { get; set; }
        public string desmaesgen { get; set; }
        public string abrevia { get; set; }
        public string parm1maesgen { get; set; }
        public string parm2maesgen { get; set; }
        public string parm3maesgen { get; set; }
        public string parm4maesgen { get; set; }
        public string parm5maesgen { get; set; }
        public string parm6maesgen { get; set; }
        public string einvoice { get; set; }
        public string statemaesgen { get; set; }
        public string tipomaesgen { get; set; }
    }
}
