
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Franquisia1._1
{

using System;
    using System.Collections.Generic;
    
public partial class numpos
{

    public string CODCIA { get; set; }

    public string PUNEMI { get; set; }

    public Nullable<int> NUMERO { get; set; }

}

}
