//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class preconven
    {
        public int secue { get; set; }
        public string codcia { get; set; }
        public string sucursal { get; set; }
        public string conventa { get; set; }
        public string codmon { get; set; }
        public Nullable<decimal> precio { get; set; }
        public System.DateTime cdate { get; set; }
        public string chora { get; set; }
        public string cuser { get; set; }
        public string state { get; set; }
    }
}
