//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class setupmail
    {
        public string NOMMAIL { get; set; }
        public string DIRMAIL { get; set; }
        public string POPMAIL { get; set; }
        public string SMTPMAIL { get; set; }
        public string USUMAIL { get; set; }
        public string PASSMAIL { get; set; }
        public string SPA { get; set; }
        public string AUTENTICACION { get; set; }
        public string PUERTO_POP3 { get; set; }
        public string PUERTO_SMTP { get; set; }
        public string CONEXION_SSL { get; set; }
        public string CONEXION_CIFRADA { get; set; }
    }
}
