
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Franquisia1._1
{

using System;
    using System.Collections.Generic;
    
public partial class tdcom
{

    public string IDCIA { get; set; }

    public string FORM { get; set; }

    public string TD { get; set; }

    public string DH { get; set; }

    public string FECVEN { get; set; }

    public string PREDETERMINADO { get; set; }

    public string AFECTO_IGV { get; set; }

    public string AUTONUM { get; set; }

    public string AFECTO_RENTA { get; set; }

    public string AFECTO_IMP_RENTA { get; set; }

    public string IS_MP { get; set; }

}

}
