//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class undatencion
    {
        public string CODCIA { get; set; }
        public string SUCURSAL { get; set; }
        public string DIVATENCION { get; set; }
        public string CODIGO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
    }
}
