//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class venc
    {
        public string CODCIA { get; set; }
        public string CODIGO { get; set; }
        public string SUCURSAL { get; set; }
        public string PUNEMI { get; set; }
        public string PROC_VENTA { get; set; }
        public string TIPO { get; set; }
        public string PRG { get; set; }
        public string PRGPS { get; set; }
        public string PERIODO { get; set; }
        public Nullable<System.DateTime> FECMOV { get; set; }
        public string MES { get; set; }
        public string CTAVEN { get; set; }
        public string SUBVEN { get; set; }
        public string TIPOMOV { get; set; }
        public string CODMOV { get; set; }
        public string TIPANE { get; set; }
        public string CODANE { get; set; }
        public string DIRECCION { get; set; }
        public string TIPDOC { get; set; }
        public string NUMDOC { get; set; }
        public string FECDOC { get; set; }
        public string FECVEN { get; set; }
        public string TIPOVENTA { get; set; }
        public string FORVENTA { get; set; }
        public string GLOSA { get; set; }
        public string CTIPCONV { get; set; }
        public Nullable<decimal> CTIPCAM { get; set; }
        public string CFECCAM { get; set; }
        public Nullable<System.DateTime> CDATE { get; set; }
        public string CHORA { get; set; }
        public string CUSER { get; set; }
        public string CSIT { get; set; }
        public string IS_GR_REMITENTE { get; set; }
        public string GR_REMITENTE { get; set; }
        public string TIPDOC_GR_REMITENTE { get; set; }
        public string GR_TRANS { get; set; }
        public string RAZON_TRANS { get; set; }
        public string RUC_TRANS { get; set; }
        public string NOM_TRANS { get; set; }
        public string LIC_TRANS { get; set; }
        public string PLACA_TRANS { get; set; }
        public string PARTIDA { get; set; }
        public string LLEGADA { get; set; }
        public string FECEMI_GR_REMI { get; set; }
        public string FECTRAS { get; set; }
        public string TIPO_TRAS { get; set; }
        public string ALBARAN { get; set; }
        public string OC_CLIENTE { get; set; }
        public string FEC_OC_CLIENTE { get; set; }
        public string TIPTAS_DETRA { get; set; }
        public Nullable<decimal> IMPTAS_DETRA { get; set; }
        public Nullable<decimal> BASE_DETRA { get; set; }
        public string TIPTAS_PERCEP { get; set; }
        public Nullable<decimal> IMPTAS_PERCEP { get; set; }
        public Nullable<decimal> BASE_PERCEP { get; set; }
        public string CSUBDIA { get; set; }
        public string CCOMPRO { get; set; }
        public Nullable<decimal> PORC_DETRA { get; set; }
        public Nullable<decimal> PORC_PERCEP { get; set; }
        public string CODMON { get; set; }
        public string FECHA_EMBARQUE { get; set; }
        public string ANEXO_PAGO_EXPORTACION { get; set; }
        public string EMBARQUE { get; set; }
        public string MARCAS { get; set; }
        public string PUERTO_ORIGEN { get; set; }
        public string PUERTO_DESTINO { get; set; }
        public Nullable<decimal> PESO_BRUTO { get; set; }
        public Nullable<decimal> PESO_NETO { get; set; }
        public string CONTENEDORES { get; set; }
        public string DESCRI_FINAL_EXPORTACION { get; set; }
    }
}
