//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Franquisia1._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vend
    {
        public vend()
        {
            this.ALMA = string.Empty;
            this.CODARTI = string.Empty;
            this.LOTE = string.Empty;
            this.DESARTI = string.Empty;
            this.UNIDAD = string.Empty;
            this.TIPOPRECIO = string.Empty;
            this.GLOSA = string.Empty;
            this.GRAVADO = 0;
            this.EXONERADO = 0;
            this.INAFECTO = 0;
        }
        public string CODCIA { get; set; }
        public string CODIGO { get; set; }
        public string ITEM { get; set; }
        public string ALMA { get; set; }
        public string CODARTI { get; set; }
        public string IS_LOTE { get; set; }
        public string LOTE { get; set; }
        public string DESARTI { get; set; }
        public string UNIDAD { get; set; }
        public string TIPOPRECIO { get; set; }
        public decimal PREUNI { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal PORCDESC { get; set; }
        public decimal DESCUENTO { get; set; }
        public decimal TOTAL { get; set; }
        public decimal IGV { get; set; }
        public decimal ISC { get; set; }
        public decimal IVAP { get; set; }
        public decimal SERVICIO { get; set; }
        public decimal NETO { get; set; }
        public string GLOSA { get; set; }
        public string TIPSERVEN { get; set; }
        public string PARTE_ALMA { get; set; }
        public Nullable<decimal> DTIPCAM { get; set; }
        public Nullable<decimal> NETO_MN { get; set; }
        public Nullable<decimal> SUBTOTAL_MN { get; set; }
        public Nullable<decimal> DESCUENTO_MN { get; set; }
        public Nullable<decimal> TOTAL_MN { get; set; }
        public Nullable<decimal> NETO_US { get; set; }
        public Nullable<decimal> SUBTOTAL_US { get; set; }
        public Nullable<decimal> DESCUENTO_US { get; set; }
        public Nullable<decimal> TOTAL_US { get; set; }
        public string ORDEN_VENTA { get; set; }
        public string ITEM_ORDEN_VENTA { get; set; }
        public string CONVENTA { get; set; }
        public string TIPOVALORVENTA { get; set; }
        public Nullable<decimal> GRAVADO { get; set; }
        public Nullable<decimal> EXONERADO { get; set; }
        public Nullable<decimal> INAFECTO { get; set; }
        public Nullable<decimal> EXPORTACION { get; set; }
        public Nullable<decimal> GRATUITA { get; set; }
        public string ROL { get; set; }
    }
}
