
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Franquisia1._1
{

using System;
    using System.Collections.Generic;
    
public partial class venpag
{

    public string CODCIA { get; set; }

    public string CODIGO { get; set; }

    public string ITEM { get; set; }

    public string FORVENTA { get; set; }

    public string FORPAGO { get; set; }

    public string TARJETA { get; set; }

    public string REFERENCIA { get; set; }

    public Nullable<decimal> IMPORTE { get; set; }

    public Nullable<decimal> RECIBIDO { get; set; }

    public Nullable<decimal> VUELTO { get; set; }

}

}
